name: Crirced CI

on:
  push:
    branches: "*"

jobs:
  check-format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.6.0
          - 1.6.2
          - 1.7.0
        experimental:
          - false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.6.2
      - name: Format
        run: crystal tool format --check

  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.6.0
          - 1.6.2
          - 1.7.0
        experimental:
          - true
    runs-on: ubuntu-latest
    env:
      CIRCED_TEST: true

    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      # - uses: getong/elasticsearch-action@v1.2
      #   with:
      #     elasticsearch version: '8.1.2'
      #     host port: 9200
      #     container port: 9200
      #     host node port: 9300
      #     node port: 9300
          # discovery type: 'single-node'
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.7.0

      - name: Set up Crystal cache
        uses: actions/cache@v2
        id: crystal-cache
        with:
          path: |
            ~/.cache/crystal
            lib
          key: ${{ runner.os }}-crystal-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-

      - name: Install shards
        if: steps.crystal-cache.outputs.cache-hit != 'true'
        run: shards check || shards install

      - name: Run tests
        run: crystal spec
